name: CD Workflow
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ingestion_modules/*'
      - 'rxnorm_modules/*'
      - 'pediatric_adr_ddi_transforms/*'
      - '.github/workflows/cd_wf.yml'
jobs:
  deploy-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: install databricks cli
        uses: databricks/setup-cli@main
      - name: install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      - name: deploy bundle
        run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DBT_ACCESS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev